jtv/libpqxx

- src/binarystring.cxx
Throwing std::bad_alloc without setting std namespace.
> Fixed unescape function on WIN32 platform

- include/pqxx/field.hxx
OPTIONAL template param collides with a preprocessor definition with the same name under MSYS2 MinGW64 compiler. This may also affect other MinGW64 builds, like Cygwin (not verified). To avoid the collision the parameter is renamed to OPTIONAL_T, which fixes the build under MSYS2.
> Rename OPTIONAL template param to fix collision under MSYS2/MinGW64

- src/strconv.cxx
Object created by std::locale("C") is equal to pre-constructed object available by std::locale::classic()
> Speedup from_string_float, to_string_fallback

- doc/libpqxx.xml
There is a error in parsing this file:
> XML Parsing Error: mismatched tag. Expected: </chapter>.
> Location: file:///home/src/libpqxx/doc/libpqxx.xml
> Line Number 45, Column 7:    </section>
> ------^
> Fixed a mismatched tag in the doc/libpqxx.xml 

- configure
- configure.ac
- src/connection_base.cxx
The implementation of 'wait_fd' (inside 'connection_base.cxx') always
relies on the existence of the 'timeval' structure. In Linux, this
structure is provided by the header 'sys/time.h'. If polling or select
capabilities are detected, the structure is never included into the
source and will result in a compilation error (GCC 7.x):
connection_base.cxx:1153:28: error: ‘{anonymous}::tv_milliseconds’ declared as an ‘inline’ variable
inline int tv_milliseconds(timeval *tv = nullptr)
^~~~~~~
...
The following moves the 'HAVE_SYS_TIME_H' check outside the
select-fallback case so that the header can be included no matter the
event-function feature is used.
- Compile check on Fedora 27 x86_64 GCC 7.2.1 GLIBC.
- Compile check on Fedora 27 x86_64 MUSL 2017.11-RC1 toolchain.
- See also [Buildroot …
> include sys/time.h outside fallback select

- include/pqxx/except.hxx
private inheritance hides `.what()`
> fixed unexpected_rows inheritance mode

- src/transaction_base.cxx
The `failure` is created from an empty string, this PR changes it to use the error message saved in `Err` instead.
> Use error message when throwing exception

- win32/vc-libpqxx.mak
The additional quoting in .mak file prevents user from using quoted paths in 'common' file. The default path for PostgreSQL on Windows for prebuilt packages contains space and it's natural a user may want to use quotes, but it will lead to an error like this:
```
copy ""C:\Program Files\PostgreSQL\10"\lib\libpq.dll" "lib"
The system cannot find the file specified.
NMAKE : fatal error U1077: 'copy' : return code '0x1'
```
This PR fixes such situation
> Fix excessive quoting in copy path

- src/connection_base.cxx
Fix for #63 
This still does not fix the issue that when using ./configure in Windows at least in MSYS2/MingW i686 the _WIN32_WINNT is not set to the correct Windows version.
> Use WSAPoll only on win version >= 0x0600

- include/pqxx/internal/statement_parameters.hxx
- include/pqxx/transaction_base.hxx
This avoids unnecessary copies when the user passes a big rvalue std::string, for example.
> In internal::params and transaction_base, move or forward arguments when appropriate.

- include/pqxx/transaction_base.hxx
Just noticed CI failing. Sorry about that. :)
> Fix typo: foward -> forward.

- configure.ac
- tools/extract_version
I still had a 2008 subversion copy of libpqxx. High time to try out the github releases. One change: I suppose that in the past, tar files were created with "make dist" - the advantage was that documentation was available direct from the release tar ball. In the new world of github, what is commited in the repository is distributed, therefore we all need to make our own documentation, hence hitting the problems fixed in this pull request.
> documentation build fixes

- test/unit/CMakeLists.txt
- test/unit/runner.cxx
- test/unit/test_array.cxx
- test/unit/test_binarystring.cxx
- test/unit/test_cancel_query.cxx
- test/unit/test_error_verbosity.cxx
- test/unit/test_errorhandler.cxx
- test/unit/test_escape.cxx
- test/unit/test_exceptions.cxx
- test/unit/test_float.cxx
- test/unit/test_notification.cxx
- test/unit/test_parameterized.cxx
- test/unit/test_pipeline.cxx
- test/unit/test_prepared_statement.cxx
- test/unit/test_read_transaction.cxx
- test/unit/test_result_iteration.cxx
- test/unit/test_result_slicing.cxx
- test/unit/test_row.cxx
- test/unit/test_simultaneous_transactions.cxx
- test/unit/test_sql_cursor.cxx
- test/unit/test_stateless_cursor.cxx
- test/unit/test_string_conversion.cxx
- test/unit/test_subtransaction.cxx
- test/unit/test_test_helpers.cxx
- test/unit/test_thread_safety_model.cxx
- test/unit/test_transaction_base.cxx
- test/unit/test_transactor.cxx
Note that this still fails to compile on macOS due to `std::experimental::optional` not having a public `value()` method — see [this Stack Overflow question](https://stackoverflow.com/questions/44217316/how-do-i-use-stdoptional-in-c).  That's an issue with macOS, not libpqxx, and can be the subject of a later discussion.
> Fix unit tests not compiling when libpqxx is configured with CMake

- src/array.cxx
In original code
`auto c = *here;
// Skip escapes.
if (c == '\'' || c == '\\') here++;
output.push_back(c);`
you skip content, but no escapes
> array.cxx skip escapes fix

- include/Makefile.am
- include/Makefile.in
...These two files were not added to the makefile earlier today in commit fe89b85c641816f386d46dba26719b3501ad04ce - My Docker build failed due to this, but now succeeds as normal.
> "encoding_group.hxx" and "type_utils.hxx" required in Makefile

- src/CMakeLists.txt.template
Build a shared library using CMake, `win32/libpqxx.cxx` is not included in the source file.
`win32/libpqxx.cxx` provide Windows DLL entry point.
> Added extra source for Windows DLL entry point

- include/CMakeLists.txt
- include/CMakeLists.txt.template
I get the following error after CMake out-of-source build: "include/pqxx/compiler-public.hxx(13): fatal error C1083:  cannot open include file 'pqxx/config-public-compiler.h':No such file"
I found the cause of this problem, `install(DIRECOTRY pqxx)` command in `include/CMakeLists.txt`,
If the argument is a relative path, `install` command searches the CMake source directory, but  `config-public-compiler.h` is generated under `${PROJECT_BINARY_DIR}/include/pqxx` (CMake out-of-source build has a different `PROJECT_SOURCE_DIR` and `PROJECT_BINARY_DIR`).
This problem can be solved by adding an `${PROJECT_BINARY_DIR}/include/pqxx` to `install(DIRECTORY)` command arguments.
> Fixes install missing header when using CMake out-of-source build

- cmake/config.cmake
When CMake in-source build, the source directory and the binary directory are the same.
CMake set the same value for `AC_CONFIG_H_IN` and `CM_CONFIG_H_IN`.
`file(WRITE "${CM_CONFIG_H_IN}" "")` command is clear file contents so that the generated `config-public-compiler.h` is also empty.
This problem can be avoided by changing the value of `CM_CONFIG_H_IN`.
> Improve generate config-public-compiler.h when using CMake

- include/Makefile.am
- include/Makefile.in
Closes #174 
Added `stream_from` and` stream_to` headers installed by CMake to header files installed by make.
> Fixes missing install with make

- configure.ac
As pg_config may not be available any more, a fallback to pkg-config was added.
> Pkg config support

- configure.ac
Make pkg-config the preferred/default config program by first checking for pkg-config and, if that is not available, check for pg_config.
> Make pkg config default

- include/pqxx/strconv.hxx
- include/pqxx/util.hxx
Just a couple of little things. The main bit is removal of `constexpr` where functions are dealing with `std::string` which is a not constexpr compatible.
> Fix some warnings

- win32/INSTALL.txt
Using the default Visual Studio Developer Command Prompt will fail to build with linker errors if using the x64 version of Postgres as the source. To build successfully using the x64 version of Postgres source your must run the ```nmake``` command under the "x64 Native Tools Command Prompt" instead.
I tested this process with the "x64 Native Tools Command Prompt" and built 64 bit libpqxx .lib and .dll successfully.
> Adds advice to use correct variant of the command prompt for x64 target

- win32/INSTALL.txt
Mention missing PGPASSWORD environment variable in win32/INSTALL.txt. Without this, the test suite cannot connect.
> Mention PGPASSWORD in Test Suite advice

- include/pqxx/internal/conversions.hxx
This fixes issue #209.
It turns out that the missing `inline` was the problem. I think that the definitions might end up in different translation units making it possible that the recursive call would depend on a declaration that had not yet been constructed. By making these `inline` this problem goes away because the linker will correctly merge all definitions across all translation units.
> Definitions of `type_name` must be `inline` so they are linked correctly

- src/strconv.cxx
I compiled libpqxx with vs2019 and the nmake.exe reported an error that the program tries to change a const variable in `src/strconv.cxx`, line 124. I found it in line 111 that the type of `res` is `const auto`, so I delete the `const` and passed the compilation.
> libpqxx-compile-with-vs2019

- src/CMakeLists.txt
- src/CMakeLists.txt.template
When PR #232 was submitted, it had both indentation and line-continuation using 4-column format. It should have been rebased on top of PR #234 before merging, but I did not get there in time. This PR corrects that by using tabs for line-continuations as per #234.
* `src/CMakeLists.txt{,.template}`: Use tabs for line continuations
> build: cmake: fix indentation from #232

- libpqxx.pc.in
- src/CMakeLists.txt
- src/CMakeLists.txt.template
- test/CMakeLists.txt
- test/CMakeLists.txt.template
- test/unit/CMakeLists.txt
- test/unit/CMakeLists.txt.template
This fixes several issues in the CMake build system, as discussed in #239.
1. Fixes some indentation following up from ce46fa732b11249cc0e0df01d57f7ad210ec9dd0
2. Removes the separate static and shared library targets. Instead, use `-DBUILD_SHARED_LIBS` to control which type of library to build.
3. Creates and installs symlinks for e.g. `libpqxx.so -> libpqxx-7.0.so`.
4. Fixes and installs the `libpqxx` pkg-config as part of the CMake installation. (Note that since PostgreSQL/`libpq` is a private dependency of `libpqxx`, it should not be part of the link interface for projects using `libpqxx`.)
> build: CMake pqxx improvements

- configure.ac
Previously, `PQXXVERSION` was unset and therefore empty in the output files. This sets it to the `$PACKAGE_VERSION` defined by `AC_INIT`.
* `configure.ac`: define `PQXXVERSION` as `$PACKAGE_VERSION`
**NOTE**: I have not at present regenerated the autotools output files in this PR. This is because I am using a newer version of autotools (i.e. automake 1.16.1 vs. 1.15.1), and don't want to force an update only to have the maintainer's version later downgraded. Either I can regenerate the autotools output for this PR, or the maintainer can do so.
> build: autotools: define PQXXVERSION output variable value

- CMakeLists.txt
- doc/CMakeLists.txt
- doc/CMakeLists.txt.template
Previously, only the autotools build system was able to build the documentation. This adds equivalent support for CMake-based builds.
Documentation is built as part of the default `all` target if `BUILD_DOC` is set, and the user has both `doxygen` and `xmlto` installed. By default, `BUILD_DOC=OFF`, however, so the user must explicitly enable it.
* `CMakeLists.txt`: Add `BUILD_DOC` option and `doc` subdirectory
* `doc/CMakeLists.txt{,.template}`: Add custom commands and targets for building documentation
> build: cmake: allow building documentation using CMake

- src/CMakeLists.txt
- src/CMakeLists.txt.template
`CMAKE_BINARY_DIR` refers to the top-level binary directory of the root CMake project. This is correct if `libpqxx` is not bundled as a dependency i.e. though `add_directory`, but `PROJECT_BINARY_DIR` will correctly handle this case as well.
This is the corresponding change to #256 but for the binary directory.
* `src/CMakeLists.txt{,.template}`: `CMAKE_BINARY_DIR` -> `PROJECT_BINARY_DIR`
> build: cmake: use PROJECT_BINARY_DIR instead of CMAKE_BINARY_DIR

- src/CMakeLists.txt
- src/CMakeLists.txt.template
`add_custom_target(library_symlink ALL ...)` has no dependencies on the pqxx target, the two targets may be executed in parallel by CMake.
Create symbolic link after pqxx build using `add_custom_command`.
> Fix create symbolic link

- src/CMakeLists.txt
- src/CMakeLists.txt.template
Ref #265 
This pull request has two changes.
1. Avoid create symbolic link when CMake build machine is Windows (host os).
2. Don't add version suffix to library name when building library for Windows (target os).
The important thing is that CMake takes into account different patterns of target OS and host OS (cross-compilation).
Since the host OS and the target OS are evaluated separately, for example, when building for Windows on Linux, no version suffix is ​​added to the generated Windows library.
> Avoid create symlink on windows

- doc/CMakeLists.txt
- include/CMakeLists.txt
Following the removal of `include/pqxx/doc/README.md`, references to it should be removed from the CMake files, or CMake will fail to run. This is fixed by regenerating the relevant CMake files from their corresponding templates.
Fixes #269.
* `doc/CMakeLists.txt`: regenerate from template
* `include/CMakeLists.txt`: Likewise.
> cmake: regenerate CMakeLists.txt following removal of `include/pqxx/doc/README.md`

- include/pqxx/transactor.hxx
- test/unit/test_transactor.cxx
This permits calling `pqxx::perform` on a more general set of callable[1] objects by using `std::invoke`[2] for perfect forwarding.
I originally ran into an issue while trying to port a code base using `libpqxx` v4 to the v6/v7 transactors. While using a lambda function which captures all references necessary for the transaction does work and allows modifying the referenced data, even though the function call is const-qualified[3] as necessitated by the current signature of `pqxx::perform`[4], this requires having separate, externally referenced object(s) to store the state of the transaction. Previously, it was possible to have the state fully encapsulated inside the transactor object which could be modified as a result of the transaction. This generalization allows for this possibility …
> Generalize transactor callable

- test/unit/test_stream_from.cxx
- test/unit/test_stream_to.cxx
Ref #282
Visual Studio may fail to compile if multi-byte characters are included in the source code.
This is because Visual Studio does not assume that the source code is written in UTF-8.
The workaround for this problem is to save the file in UTF-8 with BOM or use escaped characters.
> Avoid MSVC compile error

- include/pqxx/largeobject.hxx
Fixes #284 
The gist is that the read character `char_type` needs to be converted to the corresponding `int_type` through `char_traits<char>::to_int_type(c)`, and that comparison with `eof()` should always involve the `int_type`, not the `char_type`. 
`char_type` is the actual data type of the buffer elements.
`int_type` is a type that could contain at least all valid `char_type` and the `eof()`, and as such is larger than `char_type`.
> Fix handling of eof() in streambuffer underflow

- include/pqxx/doc/datatypes.md
It looks like that the example (from docs) for `nullness_traits` contains a little mistake:
```c++
namespace pqxx
{
template<> struct nullness_traits<T> : pqxx::no_null {};
}
```
, `pqxx::no_null` - template class, so it required to specify a template parameter.
```c++
namespace pqxx
{
template<> struct nullness_traits<T> : pqxx::no_null<T> {};
}
```
> Add a missed template parameter

- include/pqxx/internal/encoding_group.hxx
> Fix compile error "C2039: 'size_t': is not a member of 'std'" on MSVC

- src/connection.cxx
See my comment: https://github.com/jtv/libpqxx/issues/333#issuecomment-643681529
> Fix PQencryptPasswordConn() argument order

- test/runner.cxx
- test/test_helpers.hxx
The order of tests run is determined by the test map order, and since some tests depend on the output from previous tests, the map must be ordered based on lexicographical comparison. Using `char const*` for the map keys results in the map order being determined by the pointer order, not the lexicographical string order. Additionally, the pointer order is indeterminate since the C-string storage and static initialization order is indeterminate[1]. Thus, use a `std::string` key to create a test map in lexicographical order and run the tests in the correct order.
* `test/runner.cxx`:
- Use `std::string` for test map keys
- Fix some `include`'s
* `test/test_helpers.hxx`: Fix some `include`'s
[1] https://en.cppreference.com/w/cpp/language/initialization#Non-local_variables
> test: Properly order tests executed by test runner

- include/pqxx/field.hxx
According to the implementation of `field::view()`, common sense and some experiments, terminating zero byte is not included in size().
> Remove confusing commentary on pqxx::field::size()

- include/pqxx/doc/datatypes.md
change   
```cpp
template<> std::string const pqxx::type_name<T>{"T"};
``` 
to 
```cpp
template<> std::string const :type_name<T>{"T"};
```
> eliminate compile warning: extra qualification on member 'type_name' [-Wextra-qualification]

- include/pqxx/internal/conversions.hxx
Found while experimenting with #357
> Fix infinite recursion in writing non-null optional into stream_to

- include/pqxx/internal/conversions.hxx
Changed the overrun check to use the same logic as with std::string.
> Fix string_view into_buf overrun check fixes #362

- include/pqxx/transaction_base.hxx
- include/pqxx/zview.hxx
- src/transaction_base.cxx
According to the standard, std::string always holds null-terminated values, so it should be safe 
This ctor makes implementation of unescapeBytea method simple
```c++
std::string unescapeBytea(pqxx::zview escapedValue) {
size_t size;
auto result = PQunescapeBytea(reinterpret_cast<const unsigned char*>(escapedValue.c_str()), &size));
//this is pseudocode, result must be free'd afterwards
return std::string(reinterpret_cast<const char*>(result, size);
}
```
ctor from string literal allows changes described in #366
> Add implicit zview ctors from const std::string& and string literals

- configitems
- include/pqxx/compiler-public.hxx
When linking statically to libpqxx, using clang++, and (automatically
detected) --visibility=hidden --visibility-inlines-hidden flags,
I got the "ld: warning: direct access in function 'int pqxx::check_cast
... from file <here is my compilation unit> to global weak symbol
typeinfo for pqxx::range_error ... means the weak symbol cannot
be overridden at runtime. This was likely caused by different
translation units being compiled with different visibility settings.
I have verified it, but I had the same compilation settings.
However, reading https://gcc.gnu.org/wiki/Visibility , we see:
"Problems with C++ exceptions (please read!) Exception catching of a user
defined type in a binary other than the one which threw the exception requires
a typeinfo lookup. Go back and read that last …
> Always add visibility declarations.

- BUILDING-cmake.md
- test/CMakeLists.txt
Sometimes it's necessary to run tests against the compiled library on target (possibly cross-compiled) platform. This will add good confidence that a library is actually trustworthy on the specific platform+environment. Ultimately I'm going to port this library into _OpenWRT_ ecosystem.
So I'm adding a CMAKE option to copy the `runner` binary.
I don't add anything to `configure` since looks like it has not been updated for awhile and does not reflect all current options.
> CMake option to install test executor binary

- NEWS
- include/pqxx/blob.hxx
- src/blob.cxx
- test/Makefile.am
- test/Makefile.in
- test/unit/test_blob.cxx
New overloads for `pqxx::blob::read()`.
In pre-C++20 environments, this takes a `std::vector` as proposed by @elelel in #429.  However, it returns a `std::basic_string_view<std::byte>` as a stepping stone towards the C++20 version.  Which doesn't make a lot of sense on its own, but I think the pieces come together nicely in C++20.
In C++20 environments, it takes a `std::span<std::byte>` and returns a sub-span of it.
> New `blob::read(std::span<std::byte>)`.

- CMakeLists.txt
* libpqxx defaults CXX_STANDARD to C++17, which is only supported since 3.8.
* This sets CMP0067 to NEW, which fixes #434.
> CMake: Require version 3.8

- include/pqxx/params.hxx
MSVC will report "warning C4003: not enough actual parameters for macro 'max'" with the compile option `/WX`.
If the `windows.h` header file is included, it will be expanded as a `max` function macro, and the compilation will fail.
Prevent the macro from being expanded to avoid the problem.
> Disable `max` macro expanding

- src/robusttransaction.cxx
> Remove `unlikely` annotation before `return`

- src/strconv.cxx
Before this patch demangle_type_name() can call free() w/o preceding
malloc(), but jemalloc tries to initialize itself only on malloc(), but
not on free(), and so it will fail with the following assertion, under
osx:
<jemalloc>: ./contrib/jemalloc/include/jemalloc/internal/tsd_generic.h:145: Failed assertion: "tsd_booted"
> Make global initializers jemalloc compatible

- NEWS
- include/pqxx/array.hxx
- include/pqxx/blob.hxx
- include/pqxx/composite.hxx
- include/pqxx/connection.hxx
- include/pqxx/cursor.hxx
- include/pqxx/field.hxx
- include/pqxx/internal/result_iter.hxx
- include/pqxx/internal/statement_parameters.hxx
- include/pqxx/params.hxx
- include/pqxx/pipeline.hxx
- include/pqxx/range.hxx
- include/pqxx/result.hxx
- include/pqxx/row.hxx
- include/pqxx/strconv.hxx
- include/pqxx/stream_from.hxx
- include/pqxx/stream_to.hxx
- include/pqxx/transaction_base.hxx
- include/pqxx/transaction_focus.hxx
- include/pqxx/util.hxx
- include/pqxx/zview.hxx
- src/blob.cxx
- src/largeobject.cxx
- src/robusttransaction.cxx
- src/strconv.cxx
- src/stream_from.cxx
- src/subtransaction.cxx
- src/util.cxx
Trying not to break the ABI here; let's do that at the next major
release.
Also, remove those silly `constinit` suggestions.
> More `constexpr` and `noexcept`.

- include/pqxx/util.hxx
Trying to make lgtm accept that its warning (a false positive) is no
longer relevant.  Perhaps a PR will make it reconsider.
> Pointless change for LGTM.com.

- NEWS
- include/pqxx/connection.hxx
- include/pqxx/except.hxx
- include/pqxx/transaction_base.hxx
- src/connection.cxx
- src/except.cxx
- src/transaction_base.cxx
- test/test60.cxx
- test/test61.cxx
This part was always messy.  The development of variables support in libpqxx
revealed some warts in how PostgreSQL handled variables at the time.  They
behaved transactionally in some scenarios, but not in others.  I believe this
was cleared up later, with a clear distinction between local variables and
session variables.  If memory serves, I updated the implementation in libpqxx
but did not re-work the design.
Now it's time to do that.  It closes off a possible route to SQL injections,
and reduces complexity by dropping support for local variables.  Session
variables rightly belong on the `connection`, and supporting them there
offers real convenience.  (To set a session variable outside a transaction
you might need to create a `nontransaction` otherwise.)  But a local variable
is about …
> Rework variables.

- src/CMakeLists.txt
There was a bug in CMake that created library symlink when the CMake target name and the generated library name were different, but the library symlink was created when the two names were the same.
This bug occurred when the generated library name (`OUTPUT_NAME` property) contained a CMake generator expression (e.g. `OUTPUT_NAME=$<IF:$<PLATFORM_ID:Windows>,pqxx,pqxx-7.7>`).
If the library symlink is created when two names are the same, the source and destination of the link will have the same name, resulting in a circular reference (e.g. `libpqxx.a -> libpqxx.a`).
Avoid unexpected creation of library symlink by comparing the CMake target name with the generated library name when evaluating CMake generator expressions.
> Fix a bug that unexpectedly created library symlink

- src/CMakeLists.txt
The CMake target property `TARGET_FILE_DIR` prints unexpected paths depending on the CMake configuration. It has been reverted to `CMAKE_CURRENT_BINARY_DIR` which used to work.
> Revert the path to the library symlink to be installed

- NEWS
- include/pqxx/types.hxx
See #558.  MSVC in C++20 or C++23 mode complains without this.
> Strip `const` and `&` from `value_type`.

- NEWS
- appveyor.yml
- include/pqxx/connection.hxx
- src/connection.cxx
- src/wait.cxx
- test/unit/test_nonblocking_connect.cxx
I added an `appveyor.yml`.  This should mean I no longer have to configure appveyor in the web UI.  And more of the test is set up automatically, without awkward scripting in various convoluted languages.
But it also gave me the opportunity to get the tests running on Windows.  And guess what?  They didn't all pass!  The test for asynchronous connection (using `pqxx::connecting`) would hang.  Turns out it was completely unnecessary for libpqxx to manage blocking/nonblocking mode on the socket.  So that's fixed now.
> Get Windows tests working & passing.

- .mdl_style.rb
- .mdlrc
- BUILDING-cmake.md
- BUILDING-configure.md
- README.md
- include/pqxx/doc/accessing-results.md
- include/pqxx/doc/binary-data.md
- include/pqxx/doc/datatypes.md
- include/pqxx/doc/escaping.md
- include/pqxx/doc/getting-started.md
- include/pqxx/doc/mainpage.md
- include/pqxx/doc/mainpage.md.template
- include/pqxx/doc/parameters.md
- include/pqxx/doc/prepared-statement.md
- include/pqxx/doc/streams.md
- tools/lint
Use `mdl` (markdownlint) to check Markdown syntax and style.
Fixed most of the warnings, but had to disable or tweak a few rules to allow things I find necessary.
> Markdown lint

- NEWS
- README.md
- include/pqxx/doc/accessing-results.md
- include/pqxx/doc/streams.md
- include/pqxx/internal/result_iter.hxx
- include/pqxx/transaction_base.hxx
- test/unit/test_transaction_base.cxx
Puts all the various ways to execute an SQL command into 3 categories:
1. "exec" functions return `result` (or `row`, or `void`, depending).
2. "query" functions wrap "exec" ones, plus string conversion.
3. "stream" functions are like "query" ones, but stream the query.
To make these things fall into place, I'm renaming the recently added
`for_each()` to `for_stream()`, and providing a `for_query()` cousin.
If this works out, I hope to build a `query()` that works just like
`stream()` (but in non-streaming fashion).
Eventually, I hope `pqxx::result` can just _disappear_ from users'
consciousness.  The normal ways to execute a query will be...
* _exec0_ just for queries that return no data,
* _query_ functions for small result sets or exotic queries, and
* _stream_ functions for regular …
> Reorganise query execution functions.

- README.md
I was interested in trying out some of the code from the README.md file, but noticed a missing field in the `tx.query1` example.  When I attempted to run it I received an error.  I needed to `SELECT` both field names so that they were both available in the result set to be loaded into my c++ variables.  I assume this is just an accidental omission, so here's a pull request adding the other field name.
```
terminate called after throwing an instance of 'pqxx::usage_error'
what():  Tried to extract 2 field(s) from a row of 1.
```
> Added missing field in README.md tx.query1 example.

- .circleci/config.yml
- config/Makefile.in
- include/pqxx/stream_to.hxx
- test/unit/test_stream_to.cxx
Fixes #596.
Supports `std::optional`, `std::shared_ptr`, and `std::unique_ptr` of `std::string`, `std::string_view`, and `pqxx::zview`.  It's not the prettiest code, and some day I hope to generalise this stuff using C++20's Concepts.
> Make `stream_to` accept `optional<string_view>`.

- .circleci/config.yml
- test/unit/test_stream_from.cxx
I was too ambitious in a previous attempt.  I want to replace some text
scanning with a "find single-byte character" function specialised to the
applicable encoding.  To begin with, I want to do this in `stream_from`.
I then hope to be able to inline the scanning of character boundaries in
that function; and I hope to use "monobyte" scanning for UTF-8, since it
will never have a byte inside a multibyte character that looks as if it
were an ASCII character.  Those changes should make `stream_from` tons
faster, especially for monobyte encodings and "ASCII-safe" encodings
like UTF-8.
But that's a lot of work, with lots of opportunities to mess up.  So, as
a first step, I'm testing the glyph scanning in `stream_from` more
thoroughly.  This'll give me more confidence as I refactor the code.
> Test `stream_from` scanning better.

- NEWS
- include/pqxx/array.hxx
- src/array.cxx
- test/unit/test_array.cxx
This started out as a completely different project.  But along the way, I discovered that elements of arrays or of composite values are _never single-quoted._  If we see an element that's surrounded by single quotes, those quotes are part of the string itself.
> No such thing as single-quoted array/composite elements!

- NEWS
- cmake/config.cmake
- configitems
- configure
- configure.ac
- include/pqxx/config.h.in
- include/pqxx/internal/array-composite.hxx
- include/pqxx/internal/encodings.hxx
- requirements.json
- src/connection.cxx
- src/encodings.cxx
- src/stream_to.cxx
- test/unit/test_stream_to.cxx
The PostgreSQL project no longer supports postgres 9, so I'm dropping it off the libpqxx support list as well.
The only consequence code-wise is that libpqxx will now assume that libpq has a `PQencryptPasswordConn()`.
Actually might be nice to have a compile-time check for an acceptable libpq version.  But that's a separate project.
> Bump minimum libpq/postgres to version 10.

- NEWS
- include/pqxx/array.hxx
- include/pqxx/composite.hxx
- include/pqxx/field.hxx
- include/pqxx/internal/array-composite.hxx
- include/pqxx/internal/encoding_group.hxx
- include/pqxx/internal/encodings.hxx
- include/pqxx/range.hxx
- include/pqxx/result.hxx
- src/array.cxx
- test/unit/test_array.cxx
The `array_parser` was seriously broken (#590): SQL arrays may contain elements that have a semicolon in them... _and the back-end won't put them in quotes._  The parser would always see that as a field separator.  Same thing for commas in e.g. the SQL "box" type, which uses the semicolon as its separator but uses commas inside an object.
So I'm limiting `array_parser` for use with comma-separated types only, and planning a better, friendlier, faster, more flexible API for parsing arrays.
At the same time, I did manage to specialise `array_parser` internally to different encodings, which should make it considerably faster.  These changes will also benefit the future array parsing API.
> Overhaul array parser.  Comma-separated types only.

- include/pqxx/composite.hxx
- include/pqxx/internal/array-composite.hxx
Removes a little wart in the array/composite/range field parser.
The postgres documentation does in fact promise that if an array element is a string that contains a backslash, that element will show up in double quotes.
> Backslashes do not occur in unquoted strings.

- cmake/config.cmake
- config/Makefile.in
- configitems
- configure
- configure.ac
- include/pqxx/config.h.in
As of libpq 14, libpq-fe.h defines macros for features available in its libpq version.  That means we won't be needing a `configure` check for `PQenterPipelineMode()` after all: we can just `#ifdef` it.
> Use libpq's feature test macros.

- NEWS
- include/pqxx/field.hxx
- include/pqxx/transaction_focus.hxx
- test/test46.cxx
- test/test74.cxx
There are several reasons for this:
First, of course, I doubt many projects use them.  On top of that they don't add all that much value: it'd be easy enough to do the same things _ad hoc._
And the C++ streams library is a bit whacky.  It needs an overhaul. Time to take a step back and decouple from details that may soon change.
Implementing stream classes is complicated, poorly documented, prone to mistakes, hard in maintenance.  And _using_ streams has similar problems, especially when it comes to error handling and unexpected conditions.  It's easy to get wrong.
Finally, besides pointless operator overloading it also adds pointless inheritance.  It's just not carrying that weight.
> Deprecate `fieldstream` (and `basic_fieldstream`).

- NEWS
- include/pqxx/array.hxx
- include/pqxx/connection.hxx
- include/pqxx/except.hxx
- include/pqxx/internal/array-composite.hxx
- include/pqxx/internal/encodings.hxx
- include/pqxx/result.hxx
- src/except.cxx
- test/unit/test_array.cxx
Fixes #590.
A new attempt at array parsing, making more use of promises SQL's array type makes:
* All elements are of the same type, so we build in conversion.
* Arrays are regularly sized: each row is as long as any other.  Each column is as long as any other.
* Rows or columns cannot be null.
* And therefore, an array starts with as many opening braces as it has dimensions.  (Same for closing braces.)
> WIP: New array API

- include/pqxx/array.hxx
- test/unit/test_array.cxx
Further to the work on #590.
Implementing simple array iteration.  And when I say "simple," I really mean the simplest I could do: storage-order iteration, going through all dimensions.
The alternative would be to define something like a multidimensional subrange, and iterate over those.  In the two-dimensional case, that would be like iterating a `result` to get `row` elements, and then iterating each `row` to get the `field` elements.  But would it really be all that useful?  It's a lot of code overhead and cognitive load, both on the libpqxx side and on the application side.  I don't want all that complexity again — streaming queries have gotten us away from that for query results and it's been wonderful.  Plus, in practice, all you may want is to iterate over a one-dimensional array. …
> Iterate `pqxx::array`.

- include/pqxx/cursor.hxx
- src/cursor.cxx
These were defined out-of-line in order to work around an incredibly long-standing Visual C++ bug: the trouble mentioning any function called `min()` or `max()` without preparatory preprocessor magic.
There is another way to work around this: parenthesise the function name.  Using this lets us declare the functions as inline, `constexpr`, and `noexcept` which should make them a little more efficient.
> Inline cursor `all()`/`backwards_all()`.

- NEWS
- include/pqxx/zview.hxx
This is a silly problem to have.  In a way it's good.  Sometimes gcc
warns (and in my development builds, warnings are errors!) that some
`zview` constructors throw no errors, and would I perhaps like to slap
a `noexcept` on them?
A _fine_ idea, were it not for the facts that (1) `pqxx::zview` extends
`std::string_view`, and (2) the corresponding `string_view` constructor
does not have the `noexcept`.  So... can I make that promise myself?
Turns out I can.  Looking at gcc's `string_view` implementation I see
that it does declare those constructors as `noexcept`.  All I had to do
was declare my constructors as "`noexcept` provided that `string_view`
is okay with it.")
> Make more `zview` constructors `noexcept`.

- NEWS
- include/pqxx/stream_from.hxx
- src/stream_from.cxx
This makes streaming queries just very slightly faster.  At most 5% or
so.  Nothing too impressive, but now that streaming queries are beating
similar libpq queries, I find myself really motivated to optimise it!
> Use `std::memcpy()` in `stream_from`.

- config-tests/sleep_for.cxx
- include/pqxx/internal/header-pre.hxx
C++20 removes the `<ciso646>` header.  Prior to that, it was something you included "just in case."
> Unimportant ciso646-related tweaks.

- NEWS
- include/pqxx/array.hxx
- include/pqxx/internal/array-composite.hxx
- include/pqxx/internal/encoding_group.hxx
- include/pqxx/internal/encodings.hxx
- src/array.cxx
- src/encodings.cxx
Four Japanese encoding groups were really just two encoding groups.
> Merge identical encoding groups.

- test/unit/test_transaction_base.cxx
Got a strange "may be used uninitialized" warning while compiling on Debian with gcc 10.2.1, in maintainer mode.  This fixes it.
> Work around mysterious warning.

- NEWS
- config-tests/sleep_for.cxx
- include/pqxx/array.hxx
- include/pqxx/field.hxx
- include/pqxx/internal/array-composite.hxx
- include/pqxx/internal/encodings.hxx
- include/pqxx/internal/libpq-forward.hxx
- include/pqxx/version.hxx
- include/pqxx/zview.hxx
- src/result.cxx
- src/stream_from.cxx
- test/test_types.hxx
See #456.  Starting streaming replication was not something people were using libpqxx for.  There's a new (well... _relatively_ of course) result status code for that, which we weren't handling yet.
Also added the other "new" status codes, and more helpful errors.
> Handle status code for starting replication.

- src/result.cxx
Don't support pipeline status codes for libpq versions that don't yet define those codes in their headers.
> Check libpq headers for pipelining support.

- configitems
- include/pqxx/cursor.hxx
- include/pqxx/util.hxx
- src/connection.cxx
- src/wait.cxx
This was never urgent, because if waiting for a socket fails, the operation which the caller is waiting to perform will normally also fail.  (And if not... why report an error really?)
But, it's probably nicer to check for errors and report them.
> Check for errors after poll/select/WSAPoll.

- configure
- configure.ac
This should allow the compiler to find more bugs.
Unfortunately when I just enabled `-fanalyzer`, it found two potential null dereferences that I don't think I could fix.  I saw no mention of libpqxx code, only standard-library code, which makes it very hard to debug on my end.
Luckily the type was a giveaway: `std::vector<pqxx::zview>`.  The only item of that type is `pqxx::stream_from::m_fields`.  I just deprecated that entire class.
For now, I enabled all documented analyzers in gcc... except that one.
> Enable gcc static analysis in maintainer mode.

- include/pqxx/range.hxx
Build failed on test/unit/test_range.cpp because of what seems to be a bug in g++ < 10. It just moves the member declaration to the top of the templates. If it does not cause any other issue, might be worth for increased compatibility.
```
libpqxx/test/unit/test_range.cxx:1:
/libpqxx/include/pqxx/range.hxx:56:31: error: ‘m_value’ was not declared in this scope; did you mean ‘value’?
56 |     noexcept(noexcept(value < m_value))
|                               ^~~~~~~
|                               value
```
> Fix build on g++ version < 10.

- cmake/config.cmake
Hi,
I think CMake support for libpq is quite new and not available on all systems. It might become obsolete at some point, but for now it might be desirable to offer a fallback for finding libpq with pkg-config, which should be available on many systems.
I am not exactly sure why a policy is required for PostgreSQL, so I moved the new stuff to a separate block.
Best regards,
Sebastian
> Fallback to pkg-config when libpq is not found with CMake.

- test/unit/test_stream_query.cxx
Why didn't tools notice this before?
> Ditch an unused variable.

- NEWS
- include/pqxx/connection.hxx
- include/pqxx/internal/libpq-forward.hxx
- include/pqxx/internal/statement_parameters.hxx
- include/pqxx/internal/stream_query.hxx
- include/pqxx/internal/stream_query_impl.hxx
- include/pqxx/stream_from.hxx
- include/pqxx/util.hxx
- src/binarystring.cxx
- src/connection.cxx
- src/stream_from.cxx
- src/util.cxx
- test/test_types.hxx
- test/unit/test_blob.cxx
Thanks @KayEss for pointing out that I shouldn't be using a `std::function` as a deleter for a `std::unique_ptr`.  Using ordinary function pointers instead.
Also, finally figured out how to work around a bunch of gcc compile errors when I combined...
* The address sanitizer or "asan" (`-fsanitize=address`).
* Warnings as errors (`-Werror`).
* Uninitialized analyzer (`-Wanalyzer-use-of-uninitialized-value`).
Unfortunately, the combination of audit mode (`--enable-audit` in the `configure` script) and maintainer mode (`--enable-maintainer-mode` in the `configure` script) got us into exactly that combination.
It would seem that there's a problem with gcc.  It doesn't happen in clang.  I worked around it by replacing the one regex in the code with a manual parsing loop like I used to have.
> Fix `std::functional` problems.

- NEWS
- include/pqxx/internal/conversions.hxx
- include/pqxx/strconv.hxx
Fixes #681.
WHen building libpqxx as a shared library on Debian with gcc 12, any program that included libpqxx headers (with a few exceptions) would crash after `main()` returned.
There was an error message:
_free(): double free detected in tcache 2_
The problem turned out to be triggered by the inlining of any specialisation of `pqxx::type_name`, as we did in the macro `PQXX_DECLARE_ENUM_CONVERSION`.  There's a header that uses that macro, thus triggering the problem.
> Fix "double free" crash when building as shared.

- NEWS
- include/pqxx/internal/header-pre.hxx
Fixes #680.
C++17 compilers should not need this header.  (Visual Studio complains if we include this anyway, even if it's only in the case where the file actually exists.  It suggests a way to disable that warning, but it does not seem to work.)
> Stop including `<ciso646>`.

- autogen.sh
- tools/deprecations
- tools/extract_version
- tools/format
- tools/lint
- tools/todo
Adds `shellcheck` to lint script.  And fixes up pre-existing lint.
> Run shellcheck if available.

- NEWS
- configure
- include/pqxx/except.hxx
- include/pqxx/transaction_base.hxx
- include/pqxx/transactor.hxx
- src/except.cxx
- src/result.cxx
- test/unit/test_prepared_statement.cxx
- test/unit/test_transactor.cxx
See #686.  This is not a full implementation of what is suggested there. But it will enable a program to avoid the problem of catching a `broken_connection` and retrying ad infinitum.
> New exception subclass: `protocol_violation`.

- NEWS
- include/pqxx/except.hxx
- src/except.cxx
> Retire unused `blob_already_exists` exception.

- NEWS
- include/pqxx/internal/conversions.hxx
- include/pqxx/strconv.hxx
- test/test_types.hxx
- test/unit/test_blob.cxx
Should help with problems like #695.
This is really just an attempt to produce slightly more helpful errors when clients try to convert types that libpqxx deliberately does not support, such as `char`.  We're talking about conversions that leave too much to the imagination: a `char` can be signed integral value, or an unsigned integral value, or a byte of text in some encoding.
> Forbid conversion of certain types.

- configure
- configure.ac
In "maintainer mode," with a gcc-compatible compiler, the configure script tries to enable lots of warning options.  Some of these have been present in gcc and clang forever, so we just add them blindly.  Others it tries out first, to see whether the compiler accepts them.
A few of these are now old enough that I'll just enable them.  Shaves a fraction of a second off the configure step.
> Skip pointless compiler option checks.

- NEWS
- include/pqxx/internal/stream_query.hxx
- include/pqxx/internal/stream_query_impl.hxx
- include/pqxx/pipeline.hxx
- include/pqxx/stream_from.hxx
- include/pqxx/stream_to.hxx
- include/pqxx/transaction_focus.hxx
- src/pipeline.cxx
- src/stream_from.cxx
- src/stream_to.cxx
- src/transaction_base.cxx
- test/unit/test_stream_to.cxx
Fixes #706.
Finally biting the bullet and supporting moves of `transaction_focus`, which requires dealing with that backpointer from the transaction back to the focus object.
> Support moving of `stream_to`.

- include/pqxx/blob.hxx
- include/pqxx/strconv.hxx
> There is no `PQXX_HAVE_RANGES`.

- NEWS
- include/pqxx/internal/conversions.hxx
- test/unit/test_zview.cxx
Fixes one part of #728: the `to_buf()` for `zview` was broken.
> Fix bad `zview` string conversion.

- NEWS
- include/pqxx/result.hxx
- src/result.cxx
Some minor updates to the work done in #727:
* Check for errors coming from `PQfsize()`.
* Document that `PQfmod()` does not report errors.
> Tweaks to `PQfsize()` & `PQfmod()` support.

- NEWS
- include/pqxx/internal/conversions.hxx
- test/unit/test_string_conversion.cxx
Fixes #728.
I've been reluctant to implement this because it could pose a larger
runtime cost than the caller might expect.  We need to copy the whole
underlying string into the available buffer just to ensure termination.
But as the bug shows, users may need the conversion in order to pass
arrays of `string_view` as statement parameters.
> Permit conversion to string of `std::string_view`.

- .circleci/config.yml
- .github/workflows/codeql.yml
- tools/lint
Apparently Ubuntu has a "snap" for `ruff`, but it doesn't seem to be working in 23.10.  So, just `pip install` both ruff and pyflakes if they are not installed.
> Run `ruff`.  Also, `pip install` Python linters.

- .readthedocs.yaml
- NEWS
- include/pqxx/field.hxx
- include/pqxx/result.hxx
- include/pqxx/row.hxx
- include/pqxx/transaction_base.hxx
Fixes: #757
It's not really very clear where users can find out how to define new conversions.  This patch brings it up where it's relevant.
Also, readthedocs made some changes and left me with a broken docs build.  Trying to fix that as well.
> Install `dot`, try linking from header to `datatypes.md`.

- NEWS
- include/pqxx/connection.hxx
- include/pqxx/field.hxx
- include/pqxx/params.hxx
- include/pqxx/row.hxx
- include/pqxx/stream_to.hxx
- include/pqxx/transaction_base.hxx
- include/pqxx/types.hxx
- test/unit/test_transaction_base.cxx
Fixes #646.
The new functions do not have "params" in their names.  I'm hoping to get to a future where parameterised calls and regular calls look alike, except that the parameterised calls take an extra `params` argument.
Perhaps in a later stage after that, we can pass parameter packs so the parameters don't have to be wrapped up in a `params`.  But that's for later; it complicates the situation with `std::source_location` parameters which I also want to add, in 8.0.
> Parameterised versions of `query()` etc.

- NEWS
- include/pqxx/internal/stream_query_impl.hxx
- include/pqxx/row.hxx
Fixes: #771.
With these changes, the result of `transaction_base::stream()` now implements the `std::input_iterator` concept.  It should now work as a `std::range` in a C++ pipeline.
> Make streaming query result an `input_iterator`.

- NEWS
- config/Makefile.in
- configure
- include/pqxx/connection.hxx
- include/pqxx/doc/streams.md
- include/pqxx/internal/stream_query.hxx
- include/pqxx/internal/stream_query_impl.hxx
- test/unit/test_stream_query.cxx
- test/unit/test_string_conversion.cxx
Fixes #774.
The streaming code assumed that a line of `COPY` data will never end in an empty line.
> Stream rows ending in empty string properly.

- src/connection.cxx
I _think_ `PQfinish()` simply does nothing if you pass it a `nullptr`. But I don't actually see that documented anywhere, so...
> Avoid double `PQfinish()`, just in case.

- src/CMakeLists.txt
This will improve consistency between different ways of adding libpqxx to the project (specifically between `find_package(libpqxx)` and `add_subdirectory(/subproject/path)`)
There is a minimalistic batch manager for cmake that is a thin wrapper over FetchContent, with some improvements - [CPM.cmake](https://github.com/cpm-cmake/CPM.cmake.git). It has the ability to check for an installed version via find_package() before loading a package and the lack of consistency between find_package() and add_subriddectory() breaks the beauty of the code.
```cmake
CPMAddPackage(
NAME libpqxx
GIT_TAG 7.8.1
GITHUB_REPOSITORY jtv/libpqxx
)
target_link_libraries(${PROJECT_NAME} PRIVATE libpqxx::pqxx) # fail with add_subdirectory(), success with find_package()
target_link_libraries(${PROJECT_NAME} PRIVATE …
```
> [CMAKE] Adding allias for pqxx target

- tools/lint
The logic for calling `ruff` _and/or_ `pyflakes` _or_ `pyflakes3` got too tedious.  Just `pip install` them every time and we know what to count on.
And since we'll then always have the virtualenv, this also installs clang-tidy in there, rather than looking for it installed with the OS.
> Just always `pip install ruff pyflakes3`.

- NEWS
- include/pqxx/binarystring.hxx
- include/pqxx/blob.hxx
- include/pqxx/connection.hxx
- include/pqxx/doc/accessing-results.md
- include/pqxx/doc/binary-data.md
- include/pqxx/doc/prepared-statement.md
- include/pqxx/field.hxx
- include/pqxx/internal/conversions.hxx
- include/pqxx/params.hxx
- include/pqxx/strconv.hxx
- include/pqxx/transaction_base.hxx
- include/pqxx/util.hxx
- src/blob.cxx
- src/connection.cxx
- src/params.cxx
- src/util.cxx
- test/test62.cxx
- test/unit/test_binarystring.cxx
- test/unit/test_blob.cxx
- test/unit/test_escape.cxx
- test/unit/test_prepared_statement.cxx
Not sure what style you'd prefer the docstrings in (`byte_string` or `pqxx::byte_string`).  
We could also name these `pqxx::bytes` and `pqxx::bytes_view` to allow switching to `std::vector<std::byte>` and `std::span<std::byte>` in the next major version that bumps the C++ requirement without ending up with incorrect names for them.
---
Standard does not require a generic implementation. libc++ has deprecated its in version 18 and will remove it in version 19.
Replace with type aliases that will use a custom char_traits for libc++ 18 and newer. This is made conditional for libc++ 18 and newer only as this is a source breaking change.
Fixes: #726
> Use a custom std::char_traits<byte> for implementations lacking a generic implementation

- doc/_static/readme.txt
- doc/conf.py
It looks like some things that used to be optional (`language` and the directory for static HTML files) are now required.
> Fixes for the documentation build.

- NEWS
- include/pqxx/field.hxx
- include/pqxx/util.hxx
Patches up some very minor details after merging @tambry's great contribution in #751.
After this I'll run the automatic formatter as well.
> Some minor tweaks for `char_traits` work.

- include/pqxx/util.hxx
Like `length()`, these functions make no sense for binary data.  So we're better off risking a link error by leaving them undefined, than defining them and risking them actually gettnig used.
> Drop more unused `char_traits<std::byte` functions.

- .readthedocs.yaml
See #802.  The readthedocs site made some changes recently, and it broke the docs build..  So I fixed that, but now the main indexes are missing!
I have no idea how to fix this.  Just going over things that might help.
> Trying to get readthedocs index back

- NEWS
- include/pqxx/internal/conversions.hxx
- test/unit/test_array.cxx
- test/unit/test_stream_to.cxx
Fixes: #816.
The generic conversion to an SQL array computed its budget just slightly too tightly, which only became obvious when converting an array of at least 4 empty strings.
> Fix bad conversion of array-of-strings to string.

- src/blob.cxx
Was calling a static function on an instance.
> Fix one lint warning.

- NEWS
- include/pqxx/internal/conversions.hxx
- src/strconv.cxx
- test/unit/test_strconv.cxx
Fixes #807.
Type names for user-defined enums are stored as `std::string_view`, not as `std::string` like the others.  (Both are `inline` though.)
The problem did not affect the conversion as such, and that is why a pure unit test was not enough to catch it.  But it did show up when converting a `pqxx::field` value.
> Fix compile error in `field` enum support.

- tools/splitconfig.py
_In practice_ this mistake seems to have had no consequences at all. However it remains a bug, and it deserves to be fixed.
> Fix mistake in `splitconfig.py`.

- include/pqxx/connection.hxx
- include/pqxx/result.hxx
- include/pqxx/row.hxx
- include/pqxx/transaction.hxx
- include/pqxx/transactor.hxx
- tools/extract_version
There were still a few tabs here and there.  I guess clang-format doesn't clean those up.
> Get rid of tabs in code.

- doc/Doxyfile
The clang-assisted parsing in Doxygen is supposed to be slower but more accurate.
However I find that it just leads to tons of ridiculous errors, showing a complete and radical lack of comprehension of the code it's parsing. Seems to be failing to expand macros.
> Disable clang-based parsing in Doxygen.

- doc/CMakeLists.txt
Relative directories for the CMake `install` `DIRECTORY` command are interpreted with respect to the current source directory [1], whereas the `doxygen-html` output is generated in the current binary directory. So use the `CMAKE_CURRENT_BINARY_DIR` variable to specify the correct `doxygen-html` build output directory for installation. Also add a trailing slash to avoid appending the `doxygen-html` directory to the destination directory.
* `doc/CMakeLists.txt`: fix `doxygen-html` build output directory
[1] https://cmake.org/cmake/help/latest/command/install.html#directory
> doc: fix doxygen-html build output directory

- doc/Makefile.am
- doc/Makefile.in
- include/pqxx/doc/mainpage.md
The `docs` target copies the header files into the build tree, so that doxygen can find them.  But that turns out to cause trouble for regular development: the `docs` target gets built even when not configured to build documentation, so you're always compiling using copies of the header files.  A real pain when editing those.
For now, just skip the copying when not configured to build the docs. In a later iteration we can do something more sensible such as copy the headers and the source files to a different location in the build tree.
> Only copy headers to source tree if building docs.

- NEWS
- include/pqxx/stream_to.hxx
Fixes: https://github.com/jtv/libpqxx/issues/853
This has been broken (at compile time!) for _years_ but someone finally noticed.  It's a deprecated constructor, so perhaps I ought to delete it rather than fix it.
> 853: Silly typo in obscure `stream_to` constructor.

- NEWS
- include/pqxx/array.hxx
- include/pqxx/field.hxx
- test/unit/test_array.cxx
Adds a `field` member function, `as_sql_array()`, which reads an SQL array value into a `pqxx::array`.
> #841: Support parsing a field as an SQL array.

- NEWS
- include/pqxx/internal/result_iterator.hxx
- include/pqxx/row.hxx
- test/unit/test_row.cxx
Fixes: https://github.com/jtv/libpqxx/issues/846
This involves defining `operator[]` on the iterator, which indexes at an offset: `i[n] == *(i + n)`.
Unfortunately I can't do the same for the _result_ iterator.  Way back when, unaware of this requirement, I defined array indexing on a result iterator as `i[n] == (*i)[n]`.  It made some code a lot more convenient and seemed very logical.
> Make row iterator a proper `random_access_iterator`.

- cmake/config.cmake
The following comments explains why it was added, and that indeed it is no longer needed, as such.
https://github.com/jtv/libpqxx/issues/851#issuecomment-2213649992
Note that neither of these 2 cmake modules are for public use, they are internal cmake stuff.
Nothing on the outside should use it. This was feedback given by kitware developers.
> remove a use added for a purpose which is gone in the meantime.

- cmake/config.cmake
setting the policy to new is not needed, because we demand cmake_minimum_required(VERSION 3.8) and this policy was introduced in cmake 3.3, see here : https://cmake.org/cmake/help/latest/policy/CMP0057.html
this means any newer cmake is using the new policy (unless somebody would set it to old explicitly)
> Remove unneeded cmp0057 new

- cmake/config.cmake
based upon the CMAKE_CXX_STANDARD, cmake can generate an option like : -std=c++17, -std=c++20, ...
Just before the try_compile sections are exectued, the following happens:
- CMAKE_REQUIRED_DEFINITIONS is back-up-ed
- next it gets adjusted, to contain the cmpiler option to specif the language standard, this is done by setting ${CMAKE_CXX${CMAKE_CXX_STANDARD}_STANDARD_COMPILE_OPTION}
- some exampes of that are: CMAKE_CXX17_STANDARD_COMPILE_OPTION: -std=c++17 , CMAKE_CXX20_STANDARD_COMPILE_OPTION: -std=c++20
- and that value becomes the new value for CMAKE_REQUIRED_DEFINITIONS
- next all the try_compile statements are issued
- and afterwards the CMAKE_REQUIRED_DEFINITIONS is restored
Now all of that is not needed, since the minimum cmake required is 3.8.
And in cmake 3.8 an adjustment was …
> Remove unneeded standard passing

- include/pqxx/array.hxx
- include/pqxx/internal/array-composite.hxx
- src/array.cxx
This should reduce the copying of strings in array parsing a bit. Parsing an unquoted string is really just a matter of referring to the input data, so we can use a `std::string_view` there instead of a `std::string`.
Upon reflection I don't think this breaks the ABI, since it's purely an internal call.  _Yes_ there's an externally visible symbol involved but nobody has any business calling it.
> Reduce string copying in array parsing.

- NEWS
- src/util.cxx
Fixes: https://github.com/jtv/libpqxx/discussions/879
If you try to create a new transaction focus while the transaction is already focused on something else, you get an exception whose message should tell you what's going on.
Unfortunately, due to a silly oversight, it only mentions the _new_ focus but not the _existing_ focus.
> 879: Fix error message for txn focus clash.

- NEWS
- tools/format
- tools/lint
Fixes #885.
Recent macOS systems have only `/usr/bin/true`, not `/bin/true`.
> 885: Call `true`, not `/bin/true`.

- include/pqxx/dbtransaction.hxx
- include/pqxx/doc/getting-started.md
- include/pqxx/doc/prepared-statement.md
- include/pqxx/nontransaction.hxx
- include/pqxx/notification.hxx
- include/pqxx/robusttransaction.hxx
- include/pqxx/subtransaction.hxx
- include/pqxx/transaction.hxx
- include/pqxx/transaction_base.hxx
- src/largeobject.cxx
- src/notification.cxx
- src/robusttransaction.cxx
- src/transaction.cxx
- src/transaction_base.cxx
- test/test02.cxx
- test/test10.cxx
- test/test13.cxx
- test/test89.cxx
- test/unit/test_array.cxx
- test/unit/test_errorhandler.cxx
- test/unit/test_escape.cxx
- test/unit/test_field.cxx
- test/unit/test_notification.cxx
- test/unit/test_prepared_statement.cxx
- test/unit/test_transaction.cxx
- test/unit/test_transaction_base.cxx
I've standardised on `cx` and `tx` for the typical names of a connection and a transaction, respectively.  But I've gone through a bunch of naming schemes over the almost quarter century of libpqxx, and I still found some "legacy" names.
> Clean up more legacy connection/transation names.

- include/pqxx/doc/parameters.md
- include/pqxx/doc/prepared-statement.md
Revise documentation for prepared statements and parameters.
> Update prepared/params docs.

- include/pqxx/doc/escaping.md
- include/pqxx/doc/getting-started.md
- include/pqxx/internal/statement_parameters.hxx
- include/pqxx/params.hxx
- include/pqxx/result.hxx
- include/pqxx/transaction_base.hxx
- src/connection.cxx
- src/largeobject.cxx
- src/notification.cxx
- src/result.cxx
- src/robusttransaction.cxx
- src/transaction.cxx
- src/util.cxx
- test/test46.cxx
- test/test69.cxx
- test/test76.cxx
- test/test84.cxx
- test/unit/test_array.cxx
- test/unit/test_binarystring.cxx
- test/unit/test_composite.cxx
- test/unit/test_errorhandler.cxx
- test/unit/test_notification.cxx
- test/unit/test_pipeline.cxx
- test/unit/test_prepared_statement.cxx
- test/unit/test_read_transaction.cxx
- test/unit/test_stream_from.cxx
Simply drop some documentation for deprecated items that needed careful rewrites.
> Retire references to `exec_params()` & `exec_prepared()`.

- include/pqxx/nontransaction.hxx
As seen in #891, the documentation for `nontransaction` has a part that is a bit misleading.  Committing or aborting a `nontransaction` "has no effect" as far as the database is concerned, but libpqxx itself does care.
> Clarify `nontransaction` docs.

- include/pqxx/util.hxx
In environments where `std::unreachable` is not available, we previously _asserted_ that the code was not reached.  Which I guess was useful in the early days for exposing any mixups, but doesn't really set the same expectations as `std::unreachable` itself.
So, drop that assertion.  This also gets rid of a bunch of warnings from my static checker about "this could be a `static_assert`."
> Drop assertion in workaround for `std::unreachable`.

- NEWS
- include/pqxx/internal/conversions.hxx
- include/pqxx/strconv.hxx
- src/strconv.cxx
- test/unit/test_binarystring.cxx
Fixes: https://github.com/jtv/libpqxx/issues/906
The budget calculation for the conversion from array-like types to SQL strings did not take null values into account.  (In a distant past, SQL arrays could not contain null values.)  The actual string conversion did generate a null, but the budget calculation simply tried to generate a number — which could be less than what was needed to insert the SQL `NULL` keyword.
Next, the budgeting function for `std::optional` failed to account for the possibility of the `std::optional` containing a value, but the value being a null.
Also the buffer budget calculation for arrays of unquoted-safe types was slightly too tight.  I think I've had to fix this for unsafe types in the past.
(I'm also removing an internal wrapper function for comparing …
> Fix string conversion for nulls in arrays.

- NEWS
- config/Makefile.in
- configure
- configure.ac
- doc/requirements.txt
- include/pqxx/connection.hxx
- include/pqxx/notification.hxx
- include/pqxx/transaction_base.hxx
- src/connection.cxx
- src/result.cxx
- src/transaction.cxx
- src/transaction_base.cxx
- test/test04.cxx
- test/test78.cxx
- test/test79.cxx
- test/test87.cxx
- test/unit/test_notification.cxx
No more inheritance, no more virtual functions, no more mandatory base class — just pass in a lambda or any other matching callable.
Only one handler per channel — makes the channel name the key, and you can disable a handler simply by overwriting it.
No more hassle with case-insensitive channel names.  We'll just quote them consistently.
No more logging of exceptions, to a notice-processing callback which probably just ignores the message.  Exceptions during handling now just propagate up the call chain.
> Simpler, more modern API for listen/notify.

- src/connection.cxx
- test/unit/test_notification.cxx
When move-constructing or move-assigning a connection, have any notification handlers go along as well.
> Make `listen()` follow `connection` moves.

- BUILDING-cmake.md
- NEWS
Fixes: #916.
Don't know how that typo got in there.  There was a lot of hullabaloo over CMake changes back in #851, which led to the version bump.
> Oops, minimum CMake is 3.12, not 3.28.

- config/Makefile.in
- src/binarystring.cxx
- src/result.cxx
- src/strconv.cxx
- src/util.cxx
These warnings fell into 3 categories:
1. Useful warnings — many, but already fixed.
2. _Scènes à faire_ — nothing to be done but suppress them.
3. Painful advice — implemented here, accepting a small performance cost.
One `std::free()` in `strconv.cxx` triggered _three_ clang-tidy warnings — more than could fit on one healthy line.  I didn't want blanket suppression, but as a compromise, it turned out that wildcards worked.  (Perhaps I could have gotten by with a backslash-escaped newline in that comment, but that's just gruesome.)  Blanket suppression of warning signs is of course a bad thing.
But for now... clean yet thorough lint check!
> Silence `clang-tidy` warnings.

- config/Makefile.in
- configure
- configure.ac
- test/runner.cxx
- test/unit/test_result_iteration.cxx
- test/unit/test_row.cxx
This includes a bounds check on all array-index operators.
See [GNU libstdc++ documentation](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_macros.html) for the meanings of these macros.
> Enable some gcc/clang runtime checks.

- include/pqxx/internal/conversions.hxx
- test/unit/test_array.cxx
This is a fix for https://github.com/jtv/libpqxx/issues/922 
@jtv This change passes the tests and fixes my app's crash, but I dont know the codebase well-enough to tell if there are any unintended side-effects from this - PTAL. 
Thanks!
> Bugfix: (sparse) arrays' size_buffer() - not accounting for separator for NULL values

- NEWS
- config-tests/PQXX_HAVE_ASSUME.cxx
- config-tests/PQXX_HAVE_LIKELY.cxx
- configure
This changes the feature checks fo attributes `[[assume]]`, `[[likely]]`, and `[[unlikely]]` to rely on the C++20 standard means of testing for attributes.
I may want to systematise this into a separate mechanism, so that there will be just a list of attrbutes that the configure process needs to check for.
> Use `__cpp_has_attribute()` (#928).

- configure
- src/strconv.cxx
- test/runner.cxx
I still don't have all of them solved though.  For some reason a lookup in a `std::map` also counts as using uninitialized memory.
Took the opportunity to rewrite a few other small things.
> #930: Fix memory sanitizer error, and sundry others.

- CMakeLists.txt
Hi, I think it'd be nice to skip building tests by default when libpqxx is included in other projects. For instance, with [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html):
```cmake
include(FetchContent)
FetchContent_Declare(libpqxx GIT_REPOSITORY https://github.com/jtv/libpqxx.git GIT_TAG 7.10.0)
FetchContent_MakeAvailable(libpqxx)
target_link_libraries(app PRIVATE libpqxx::pqxx)
```
Currently, projects need to set:
```cmake
set(SKIP_BUILD_TEST ON)
```
[nlohmann/json](https://github.com/nlohmann/json) is one project that does this.
> Skip building tests by default when included in other projects

- NEWS
- config/Makefile.in
- include/pqxx/doc/datatypes.md
- include/pqxx/field.hxx
- include/pqxx/internal/conversions.hxx
- include/pqxx/params.hxx
- include/pqxx/strconv.hxx
- include/pqxx/types.hxx
- include/pqxx/util.hxx
- src/strconv.cxx
- test/unit/test_string_conversion.cxx
Fixes: https://github.com/jtv/libpqxx/issues/694
Fixes: https://github.com/jtv/libpqxx/issues/827
Making much broader use of concepts.  String conversions now accept any contiguous range of `std::byte` as binary data.  Traits specialisations for integer and floating-point types are simpler now.  And you can now just convert from string to `std::string_view` (or `char const *`), so long as you don't access it after the original string's lifetime ends.
> String conversion to `string_view`.  More binary types.

- NEWS
- cmake/pqxx_cxx_feature_checks.cmake
- config-tests/PQXX_HAVE_PATH.cxx
- config-tests/no_need_fslib.cxx
- config/Makefile.in
- configitems
- configure
- include/pqxx/blob.hxx
- include/pqxx/config.h.in
- include/pqxx/connection.hxx
- include/pqxx/doc/binary-data.md
- include/pqxx/internal/conversions.hxx
- include/pqxx/params.hxx
- include/pqxx/strconv.hxx
- include/pqxx/stream_to.hxx
- include/pqxx/types.hxx
- include/pqxx/util.hxx
- include/pqxx/zview.hxx
- pqxx_cxx_feature_checks.ac
- requirements.json
- src/blob.cxx
- src/connection.cxx
- test/Makefile.am
- test/Makefile.in
- test/runner.cxx
- test/unit/test_blob.cxx
- test/unit/test_escape.cxx
- test/unit/test_util.cxx
- test/unit/test_zview.cxx
Fixes: https://github.com/jtv/libpqxx/issues/925
Extends a bunch more functions that accept `pqxx::bytes_view` with variants which accept any type that satisfies the `pqxx::binary` concept.
Also, change the `pqxx::bytes_view` type alies from being a `std::basic_string_view<std::byte>` (which doesn't actually have to work according to the standard!) to being a `std::span<std::byte>`.  This seems to be broadly compatible with existing code.  For completeness I'm adding a `pqxx::writable_bytes_view` as well.
Along the way I'm assuming support for C++17's `std::filesystem::path`, and adding a conversion to `pqxx::zview`.  With that, `pqxx::blob` no longer needs explicit support for `std::filesystem::path` filenames; it just accepts `pqxx::zview` and passing a `std::filesystem::path` will just …
> Accept `pqxx::binary` concept in more places.

- doc/Doxyfile
Now that the test directories have been unified, we no longer need to run Doxygen on `test/unit/`.
> Drop `test/unit` from Doxyfile.

- .circleci/config.yml
For some reason running Debian unstable in CircleCI has been failing for a while now, at the stage where we install packages.
Backporting these changes from the `start-8` branch.
> Use Debian testing instead of unstable for CircleCI.

- test/runner.cxx
- test/test_helpers.hxx
The code scan on GitHub was complaining about some slightly large objects were being passed as arguments in test code.
Not a huge deal, since this is test code and we're not talking about stack-threatening amounts, but fixing is better than ignoring.
There were a few others that are a bit harder to fix, and which may be gone anyway in the current 8.0 code.
> Fix some CodeQL "passing large object" warnings.

- src/CMakeLists.txt
This fixes the absolute path being in the CMake config file.
> Use imported target.

- include/pqxx/composite.hxx
- include/pqxx/internal/conversions.hxx
- include/pqxx/separated_list.hxx
- include/pqxx/util.hxx
- test/test_helpers.hxx
Fixes: https://github.com/jtv/libpqxx/issues/961
This is something I kept needing: a bounds-checking version of
std::string_view::copy(), which writes into a std::span<char>
instead of a raw pointer; which just copies the entire string without
needing an argument to say so; and which accepts an offset into the
destination buffer (not one into the source),
As I upgrade more string conversions to the libpqxx 8.0 API, I expect to
need this in many more places.
> #961: Introduce `copy_chars()` helper.

- include/pqxx/array.hxx
- include/pqxx/doc/datatypes.md
- include/pqxx/field.hxx
- include/pqxx/internal/array-composite.hxx
- include/pqxx/internal/conversions.hxx
- include/pqxx/internal/stream_query.hxx
- include/pqxx/strconv.hxx
- include/pqxx/stream_from.hxx
- include/pqxx/types.hxx
- include/pqxx/zview.hxx
- src/Makefile.am
- src/Makefile.in
- src/strconv.cxx
- src/types.cxx
- test/test_strconv.cxx
- test/test_type_name.cxx
- test/test_types.hxx
- test/test_util.cxx
Fixes: https://github.com/jtv/libpqxx/issues/959
This should make it easier to override a type name with a manually
written, human-friendly one such as `std::string` instead of the whole
`std::basic_string<char, ...>` incantation; inline those to reduce
duplication; and consistently make it a `std::string_view`.
With that latter point, it abstracts away the underlying storage.  Which does mean that sometimes with template types you may need to construct the names in a separate place just so `name_type()` can return a view.  But that's probably better than storing each individual name in its own `std::string`, and allows for more optimisations.
> #959: Replace `type_name` template with `name_type()`.

- NEWS
- include/pqxx/connection.hxx
Fixes: https://github.com/jtv/libpqxx/issues/963
The documentation for the new API didn't actually mntion that the notifications from a `listen()` only come in when the connection's `get_notifs()` or `await_notification()` are called.
> Exlain on `listen()` how/when notifications come in.

- .circleci/config.yml
- configure
- configure.ac
- include/pqxx/zview.hxx
- test/runner.cxx
- test/test_helpers.hxx
- test/unit/test_row.cxx
- test/unit/test_zview.cxx
Fixes: https://github.com/jtv/libpqxx/issues/972
> #972: Enable `-Wdeprecated-literal-operator` if supported.

- include/pqxx/field.hxx
This was a big, confused thinko that's been around since forever.
> Fix doc for `field::num()`.

- test/test_helpers.hxx
Perhaps this will shut up those misleading static analysis warnings
about the test functions being unused.  And most of all, that insane
AI helpfully trying to delete them.
> Mark test registration object as maybe-unused.

- test/test_helpers.hxx
Backport from `start-8` branch.
> Mark test registrars as `maybe_unused`.

- src/CMakeLists.txt
`get_target_property(PostgreSQL_INCLUDE_DIRS PostgreSQL::PostgreSQL INTERFACE_INCLUDE_DIRECTORIES)` is not guaranteed to work.
It is not mentioned anywhere in the documentation as a property of the `PostgreSQL::PostgreSQL` target. `PostgreSQL_INCLUDE_DIRS` is a variable automatically defined by `find_package(PostgreSQL)`.
It should be removed because if it cannot be retrieved for a property, the build will fail.
> Fix a bug `get_target_property(PostgreSQL_INCLUDE_DIRS PostgreSQL::PostgreSQL)` does not working

- include/pqxx/util.hxx
- src/strconv.cxx
Ran into a few unexpected problems compiling on a Mac with clang 17.  (This version did not have a working floating-point `charconv`, for one, so the build exercised code that my usual build environment does not.)
> Fix some errors on Mac clang17.

- include/pqxx/doc/prepared-statement.md
#888 accidentally omitted `pqxx::params` in `prepared-statement.md`. This PR adds it so the example becomes valid again (along with two typo fixes while I'm editing the file anyway)
> Fix broken prepared statement example in docs

- NEWS
- src/connection.cxx
- test/Makefile.am
- test/Makefile.in
- test/test_connection.cxx
- test/test_connection_string.cxx
Fixes: https://github.com/jtv/libpqxx/issues/992
This is still just a basic ASCII-oriented solution.  Next challenge: figure out how non-ASCII characters can get encoded.  There's mention of percent-encoding, but I'm not sure yet that that is the whole answer. 
(Would be kind of hard to support other encodings though, since you'd need some kind of shared default between the client and the server to support anything else.  I mean... you _could_ use client encoding but that would get complicated with client encodings specified by the connection string itself.)
> 992: Support spaces in connection string params.

- NEWS
- config/Makefile.in
- include/pqxx/internal/stream_query_impl.hxx
- include/pqxx/transaction_base.hxx
Fixes #997.
I could have sworn I'd already done this in 7.10.1, but evidently I had not.  Dropping the function, because the frontend/backend protocol does not seem to support this.
> Params on streaming queries are not supported.

- include/pqxx/blob.hxx
- include/pqxx/connection.hxx
- include/pqxx/internal/conversions.hxx
- include/pqxx/params.hxx
- include/pqxx/strconv.hxx
- include/pqxx/transaction_base.hxx
- include/pqxx/types.hxx
- include/pqxx/util.hxx
- include/pqxx/zview.hxx
Useful for new compiler with old C++ library.
My env is clang 20.1.8 with Ubuntu 20.04 libstdc++.
See #1017 for the discussion
> Fix ranges checks
