- ChangeLog
- doc/libpqxx.xml
- src/result.cxx
This PR fixes some very minor typos but I hope that this is a good place to start forwarding you some patches I have in the deb.
> Fixing some minor typos

- .gitignore
- include/pqxx/result_iterator.hxx
- include/pqxx/row.hxx
- win32/vc-libpqxx.mak
- win32/vc-libpqxx.mak.template
- win32/vc-test-unit.mak
- win32/vc-test-unit.mak.template
- win32/vc-test.mak
- win32/vc-test.mak.template
> [SOLVED] fixing build on VS2015

- include/pqxx/connection_base.hxx
- include/pqxx/transaction_base.hxx
This PR fixes the last errors on windows for master branch. It's now possible to build it on Win.
> Fix MSVC error C2487

- include/pqxx/basic_connection.hxx
- include/pqxx/connection.hxx
- include/pqxx/doc/getting-started.md
> Documentation for pqxx::connection() constructor

- include/pqxx/result_iterator.hxx
prefix increment operator should return a reference value.
> fix prefix increment operator declaration error 

- src/strconv.cxx
Solves issues with `dumb_stringstream` in #124.
> dumb_stringstream initialization bugfix.

- include/pqxx/internal/ignore-deprecated-post.hxx
- include/pqxx/internal/ignore-deprecated-pre.hxx
> Enable pragma GCC only when gcc compiler

- src/CMakeLists.txt
- src/CMakeLists.txt.template
> Make path relative to current cmake file.

- include/pqxx/stream_from.hxx
- include/pqxx/stream_to.hxx
- src/stream_from.cxx
This changes it to a simpler compile time list comprehension using a
c++17 fold over the comma operator.
> Refactor stream_from to remove some awkward template code

- cmake/config.cmake
- src/CMakeLists.txt
- src/CMakeLists.txt.template
- test/unit/CMakeLists.txt
- test/unit/CMakeLists.txt.template
Related https://github.com/jtv/libpqxx/issues/306#issuecomment-620998150
> Enable support CMake variable PostgreSQL_ROOT

- test/test87.cxx
Fix [this comment](https://github.com/jtv/libpqxx/issues/341#issuecomment-650388495) warning.
> Avoid redefined NOMINMAX

- include/pqxx/largeobject.hxx
Check result of cwrite in olostream
> Check olostream write result in overflow() function

- include/pqxx/binarystring.hxx
- include/pqxx/compiler-public.hxx
- include/pqxx/largeobject.hxx
- include/pqxx/stream_from.hxx
> Fix a bug that syntax error in Visual Studio 2017

- src/strconv.cxx
> Fix compiler could not find 'digit_to_number'

- include/pqxx/connection.hxx
- test/unit/test_connection.cxx
Fixes #538.
This is not meant for general use, but it helps with one very specific
use-case where an application mixes C and C++.
> Limited access to raw libpq connection.

- appveyor.yml
Appveyor now has newer postgres images available.  Use them.
> Upgrade PostgreSQL in appveyor tests.

- include/pqxx/array.hxx
- include/pqxx/field.hxx
- include/pqxx/internal/array-composite.hxx
- include/pqxx/result.hxx
- include/pqxx/row.hxx
- src/array.cxx
- src/field.cxx
- src/result.cxx
- src/row.cxx
This is an ABI-breaking change that I've been saving up.
> Make more functions `noexcept`.

- .github/workflows/codeql.yml
- src/strconv.cxx
Thanks GIthub for foisting this on us without asking.  You replaced a lovely, working LGTM.com setup with a broken Github one, and now we get to figure out what's changed and what you broke, from the wrong end of the problem, with unclear and incomplete documentation.  That's even more fun than trying to make these things work from zero.
> WIP: Get Github's new code checking working

- include/pqxx/array.hxx
I'm not proud of this.  Or wait, maybe I am.  In a guilty sort of way.  ← _(definition of "heuristic")_
But anyway, it'll save some vector reallocations which is going to make it faster.
> Pre-estimate array size to minimise allocations.

- include/pqxx/internal/encodings.hxx
In `find_ascii_char()`, remove the check for whether it's looking at a single-byte character or a multibyte one.  That check is not needed for finding an ASCII character.
There are two kinds of encoding:
"ASCII-safe" encodings, where no byte in a multibyte character will ever resemble an ASCII character.  For those, `find_ascii_char` searches all bytes one by one, ignoring where the actual character boundaries are.
"Non-ASCII-safe" encodings, where the ASCII byte value we're looking for may occur in the middle of a multibyte character... but never at the beginning of one.  For those, `find_ascii_char` only looks at the first byte of each character.
Shaves a few percent off query streaming time.
> Speed up `find_ascii_char()`.

- src/connection.cxx
- src/stream_from.cxx
Stream query results just that little bit faster yet.
> More micro-optimisations in query streaming.

- include/pqxx/range.hxx
- test/unit/test_range.cxx
Let's see to what extent we can get ranges to work at compile time.
> Make more of ranges `constexpr`.

- include/pqxx/version.hxx.template
To match formatting produced by my current version of clang-format.
> Re-indent `version.hxx.template`.

- config/Makefile.in
- include/Makefile.am
- include/Makefile.in
- include/pqxx/internal/encodings.hxx
- include/pqxx/internal/stream_query.hxx
- include/pqxx/internal/stream_query_impl.hxx
- include/pqxx/range.hxx
- src/wait.cxx
- test/unit/test_stream_query.cxx
Oops, forgot to add these files, it seems.  Broke the install in the `configure`-based build: #657
> Add missing gate headers to `Makefile.am`.

- test/unit/test_blob.cxx
Got two dozen warnings.  One of them was valid.  Some were difficult to understand.
This could be a useful product, but it'd be nice to see a bit more polish.
> Trying out PVS Studio.

- BUILDING-configure.md
- README.md
This pull request is a suggestion for clarifications that can be added to the BUILDING-configure.md file, as we discussed. Feel free to correct and/or disregard as needed.
> Blue santa

- NEWS
- include/pqxx/connection.hxx
- src/connection.cxx
- test/unit/test_connection.cxx
Been meaning to do this for ages, though there hasn't been much demand for it.  It came up again in #675.
> Support `PQinitOpenSSL()`.

- .gitignore
- include/pqxx/result.hxx
- src/result.cxx
> Added 2 functions (column_size and column_mod) under pqxx::result file

- .readthedocs.yaml
First stab at configuring this.
> Read The Docs now wants a config file.

- include/pqxx/doc/streams.md
- include/pqxx/transaction_base.hxx
This is meant to help with questions like in #644.
> Document streams in more detail.

- include/pqxx/internal/conversions.hxx
> Native support for std::span

- NEWS
- include/pqxx/connection.hxx
- include/pqxx/internal/conversions.hxx
- include/pqxx/internal/stream_query_impl.hxx
- include/pqxx/result.hxx
- include/pqxx/transaction_base.hxx
- include/pqxx/util.hxx
- src/array.cxx
- src/connection.cxx
- src/cursor.cxx
- src/encodings.cxx
- src/largeobject.cxx
- src/params.cxx
- src/pipeline.cxx
- src/result.cxx
- src/sql_cursor.cxx
- src/strconv.cxx
- src/stream_to.cxx
- src/time.cxx
- src/transaction_base.cxx
- src/util.cxx
- test/unit/test_stream_query.cxx
- test/unit/test_transaction_base.cxx
Just dotting the odd ı before the 7.9.0 release (and running a final test for luck).
> Prepare for 7.9.0 release.

- .readthedocs.yaml
- doc/requirements.txt
> Grrr.  Readthedocs graphs not working.

- cmake/config.cmake
Fixes https://github.com/jtv/libpqxx/issues/851
Thanks @tt4g.
> Deal with renamed function in CMake 3.30.

- .github/workflows/codeql.yml
Github says I need to change "v2" in this config to "v3.."
> Upgrade CodeQL github actions: v2 to v3.

- NEWS
- appveyor.yml
- include/pqxx/internal/header-pre.hxx
Build in a "matrix" so we can test against multiple language versions at the same time.
Upgrade PostgreSQL as well
> Tweak appveyor config.
